#!/usr/bin/env python3
"""
Expected-value, house-edge, and long-term-projection engine for Vietlott games.

Reads config/games.json (generated by seed_games.py) and computes EV, house
edge, long-term expected loss, and an investment-alternative comparison in VND.
This is the executable backend for the `calculate_expected_value` tool in
SKILL.md.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional

CONFIG_DIR = Path(__file__).resolve().parent.parent / "config"
DEFAULT_RETURN_RATE = 0.07


def _load_games() -> Dict:
    return json.loads((CONFIG_DIR / "games.json").read_text(encoding="utf-8"))


@dataclass(frozen=True)
class EVResult:
    game: str
    ticket_cost_vnd: int
    expected_winnings_vnd: float
    expected_value_vnd: float
    expected_loss_vnd: float
    house_edge_percent: float
    any_prize_probability: float
    calculation_steps: List[str]


def _mega_ev(games: Dict) -> EVResult:
    g = games["vietlott_games"]["mega_6_45"]
    cost = g["ticket_cost_vnd"]
    steps = []
    ew = 0.0
    for tier in g["prize_tiers"]:
        contrib = tier["prize_vnd"] / tier["odds_1_in"]
        ew += contrib
        steps.append(
            f"  {tier['prize_name']}: {tier['prize_vnd']:,} VND / 1-in-{tier['odds_1_in']:,.2f} = {contrib:,.2f} VND"
        )
    any_prize = sum(t["probability"] for t in g["prize_tiers"])
    return _finalize("Mega 6/45", cost, ew, any_prize, steps)


def _power_ev(games: Dict) -> EVResult:
    g = games["vietlott_games"]["power_6_55"]
    cost = g["ticket_cost_vnd"]
    steps = []
    ew = 0.0
    for tier in g["prize_tiers"]:
        contrib = tier["prize_vnd"] / tier["odds_1_in"]
        ew += contrib
        steps.append(
            f"  {tier['prize_name']}: {tier['prize_vnd']:,} VND / 1-in-{tier['odds_1_in']:,.2f} = {contrib:,.2f} VND"
        )
    any_prize = sum(t["probability"] for t in g["prize_tiers"])
    return _finalize("Power 6/55", cost, ew, any_prize, steps)


def _keno_ev(games: Dict, select: int) -> EVResult:
    k = games["vietlott_games"]["keno"]
    cost = k["ticket_cost_vnd"]
    tiers = k["co_ban_prize_tables"][f"select_{select}"]
    steps = []
    ew = 0.0
    for tier in tiers:
        if tier["odds_1_in"] is None:
            continue
        contrib = tier["prize_vnd"] / tier["odds_1_in"]
        ew += contrib
        steps.append(
            f"  select {select} match {tier['match']}: {tier['prize_vnd']:,} VND / 1-in-{tier['odds_1_in']:,.2f} = {contrib:,.2f} VND"
        )
    any_prize = sum(t["probability"] for t in tiers if t["prize_vnd"] > 0)
    return _finalize(f"Keno (select {select})", cost, ew, any_prize, steps)


def _max3d_ev(games: Dict, mode: str) -> EVResult:
    md = games["vietlott_games"]["max_3d"]
    cost = md["ticket_cost_vnd"]
    tiers = md["play_modes"][mode]["prize_tiers"]
    steps = []
    ew = 0.0
    for tier in tiers:
        if tier["odds_1_in"] is None:
            continue
        contrib = tier["prize_vnd"] / tier["odds_1_in"]
        ew += contrib
        steps.append(
            f"  {mode} match {tier['matches']}: {tier['prize_vnd']:,} VND / 1-in-{tier['odds_1_in']:,.2f} = {contrib:,.4f} VND"
        )
    any_prize = sum(t["probability"] for t in tiers)
    return _finalize(f"Max 3D ({mode})", cost, ew, any_prize, steps)


def _finalize(game: str, cost: int, ew: float, any_prize: float, steps: List[str]) -> EVResult:
    ev = ew - cost
    return EVResult(
        game=game,
        ticket_cost_vnd=cost,
        expected_winnings_vnd=ew,
        expected_value_vnd=ev,
        expected_loss_vnd=cost - ew,
        house_edge_percent=(cost - ew) / cost * 100.0,
        any_prize_probability=any_prize,
        calculation_steps=steps,
    )


def calculate_expected_value(game: str, keno_select: Optional[int] = None, max3d_mode: Optional[str] = None) -> EVResult:
    """Compute EV for a named Vietlott game. game in {mega, power, keno, max3d}."""
    games = _load_games()
    key = game.lower()
    if key in ("mega", "mega_6_45"):
        return _mega_ev(games)
    if key in ("power", "power_6_55"):
        return _power_ev(games)
    if key == "keno":
        if keno_select is None or not 1 <= keno_select <= 10:
            raise ValueError("keno requires keno_select in 1..10")
        return _keno_ev(games, keno_select)
    if key in ("max3d", "max_3d"):
        if max3d_mode is None or max3d_mode not in ("max_3d_single", "max_3d_plus", "max_3d_pro"):
            raise ValueError("max3d requires max3d_mode in {max_3d_single, max_3d_plus, max_3d_pro}")
        return _max3d_ev(games, max3d_mode)
    raise ValueError(f"unknown game: {game}")


@dataclass(frozen=True)
class LongTermProjection:
    weekly_spending_vnd: int
    house_edge: float
    years: int
    weekly_expected_loss_vnd: float
    annual_expected_loss_vnd: float
    total_expected_loss_vnd: float
    investment_alternative_vnd: float


def long_term_projection(weekly_spending_vnd: int, house_edge: float, years: int = 10, return_rate: float = DEFAULT_RETURN_RATE) -> LongTermProjection:
    """Project cumulative expected loss and the opportunity cost of investing the same amounts."""
    if not 0.0 <= house_edge <= 1.0:
        raise ValueError("house_edge must be a fraction in [0,1]")
    if weekly_spending_vnd < 0 or years <= 0:
        raise ValueError("weekly_spending_vnd >= 0 and years > 0 required")
    weekly_loss = weekly_spending_vnd * house_edge
    annual_loss = weekly_loss * 52
    total_loss = annual_loss * years
    annual_savings = weekly_spending_vnd * 52  # if spent on lottery, the same VND is the "saved" amount
    # Future value of an ordinary annuity.
    fv = annual_savings * (((1 + return_rate) ** years - 1) / return_rate) if return_rate > 0 else annual_savings * years
    return LongTermProjection(
        weekly_spending_vnd=weekly_spending_vnd,
        house_edge=house_edge,
        years=years,
        weekly_expected_loss_vnd=weekly_loss,
        annual_expected_loss_vnd=annual_loss,
        total_expected_loss_vnd=total_loss,
        investment_alternative_vnd=fv,
    )


def entertainment_value_comparison(weekly_spending_vnd: int) -> Dict[str, object]:
    """Compare weekly lottery entertainment spend to other VND entertainment costs."""
    # Illustrative Vietnamese-context entertainment costs (VND).
    alternatives = {
        "Xem phim (cinema ticket)": (100_000, 2.0),
        "Caphe (coffee outing)": (60_000, 1.5),
        "Bai tap the hinh/gym (1 thang)": (400_000, 30.0 * 1.0),
        "Sach truyen (1 cuon)": (120_000, 8.0),
    }
    # Lottery: assume ~3 days of anticipation per weekly spend (generous).
    hours = 3 * 24
    lottery_per_hour = weekly_spending_vnd / hours if hours else float("inf")
    out = {"lottery": {"weekly_vnd": weekly_spending_vnd, "estimated_hours": hours, "vnd_per_hour": lottery_per_hour}}
    for name, (cost, hrs) in alternatives.items():
        out[name] = {"cost_vnd": cost, "hours": hrs, "vnd_per_hour": cost / hrs}
    return out


def format_ev(r: EVResult) -> str:
    lines = [
        f"Expected Value Analysis: {r.game}",
        "=" * 60,
        f"Ticket cost             : {r.ticket_cost_vnd:,} VND",
        f"Expected winnings/ticket: {r.expected_winnings_vnd:,.2f} VND",
        f"Expected value/ticket   : {r.expected_value_vnd:,.2f} VND",
        f"Expected loss/ticket    : {r.expected_loss_vnd:,.2f} VND",
        f"House edge              : {r.house_edge_percent:.1f}%",
        f"P(any prize)            : {r.any_prize_probability:.4%}",
        "Steps:",
        *r.calculation_steps,
    ]
    return "\n".join(lines)


def main() -> None:
    for game, kw in [("mega", {}), ("power", {}), ("max3d", {"max3d_mode": "max_3d_single"})]:
        print(format_ev(calculate_expected_value(game, **kw)))
        print()
    print("Keno select 7 (lowest house edge):")
    print(format_ev(calculate_expected_value("keno", keno_select=7)))
    print()

    print("Long-term projection (200,000 VND/week, 50% house edge, 10 years):")
    proj = long_term_projection(200_000, 0.50, 10)
    print(f"  Weekly expected loss : {proj.weekly_expected_loss_vnd:,.0f} VND")
    print(f"  Annual expected loss : {proj.annual_expected_loss_vnd:,.0f} VND")
    print(f"  10-year expected loss: {proj.total_expected_loss_vnd:,.0f} VND")
    print(f"  If invested @7%/yr  : {proj.investment_alternative_vnd:,.0f} VND")

    print("\nEntertainment cost comparison (200,000 VND/week lottery):")
    cmp = entertainment_value_comparison(200_000)
    for name, data in cmp.items():
        if isinstance(data, dict):
            per = data.get("vnd_per_hour")
            print(f"  {name:32}: {per:,.0f} VND/hour")


if __name__ == "__main__":
    main()
